---
kind: pipeline
type: docker
name: automated

trigger:
  event:
    - push

steps:
- name: update
  image: plugins/git
  commands:
  - export BRANCH_NAME=update-test-$(date '+%Y-%m-%d')
  - echo $DRONE_REPO
  - sed -i 's/\(release_version *= *\).*/\1"'${DRONE_BUILD_NUMBER}'"/' ./test.tf
  - sed -i 's/\(release_version *= *\).*/\1"'${DRONE_BUILD_NUMBER}'"/' ./test2.tf
  - git add ./test.tf ./test2.tf
  - git commit -m "Test $(date '+%Y-%m-%d')"
  - git push origin HEAD:$BRANCH_NAME
  - echo $BRANCH_NAME
