---
kind: pipeline
type: docker
name: automated

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

steps:
- name: update
  image: plugins/git
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  commands:
  - export BRANCH_NAME=update-test-$(date '+%Y-%m-%d')
  - echo $DRONE_REPO
  - sed -i 's/\(release_version *= *\).*/\1"'${DRONE_BUILD_NUMBER}'"/' ./test.tf
  - sed -i 's/\(release_version *= *\).*/\1"'${DRONE_BUILD_NUMBER}'"/' ./test2.tf
  - git add ./test.tf ./test2.tf
  - git commit -m "Test $(date '+%Y-%m-%d')"
  - git remote remove origin
  - git remote add origin "https://$GITHUB_TOKEN@github.com/$DRONE_REPO.git"
  - git push origin HEAD:$BRANCH_NAME
  # - git push "https://$GITHUB_TOKEN@github.com/$DRONE_REPO.git" HEAD:$BRANCH_NAME
  - echo $BRANCH_NAME
  - echo "Test3"
# - name: git-push
#  image: appleboy/drone-git-push
#  settings:
#    # remote_name: origin
#    remote:
#      from_secret: GH_REPO
#    ssh_key:
#      from_secret: GH_SSH_KEY
#    branch: update-test-2023-03-09
#    force: true
